name: CoffeeScreen
options:
  bundleIdPrefix: com.gorita
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "14.0"
  configs:
    Debug:
      CODE_SIGN_STYLE: Automatic
      CODE_SIGN_IDENTITY: "-"
      DEVELOPMENT_TEAM: ""
    Release:
      CODE_SIGN_STYLE: Manual
      CODE_SIGN_IDENTITY: "Developer ID Application"
      DEVELOPMENT_TEAM: "${DEVELOPMENT_TEAM}"

targets:
  CoffeeScreen:
    type: application
    platform: macOS
    sources:
      - path: CoffeeScreen
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.gorita.coffee-screen
        INFOPLIST_FILE: CoffeeScreen/Resources/Info.plist
        PRODUCT_NAME: Coffee-Screen
        PRODUCT_MODULE_NAME: CoffeeScreen
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        COMBINE_HIDPI_IMAGES: YES
      configs:
        Debug:
          ENABLE_HARDENED_RUNTIME: NO
        Release:
          ENABLE_HARDENED_RUNTIME: YES
    info:
      path: CoffeeScreen/Resources/Info.plist
      properties:
        CFBundleDisplayName: Coffee-Screen
        CFBundleName: Coffee-Screen
        CFBundleShortVersionString: "$(MARKETING_VERSION)"
        CFBundleVersion: "$(CURRENT_PROJECT_VERSION)"
        LSMinimumSystemVersion: "$(MACOSX_DEPLOYMENT_TARGET)"
        NSMainStoryboardFile: ""
        NSPrincipalClass: NSApplication
        LSUIElement: false
    entitlements:
      path: CoffeeScreen/Resources/CoffeeScreen.entitlements
      properties:
        com.apple.security.app-sandbox: false

  CoffeeScreenTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: CoffeeScreenTests
        excludes:
          - "**/.DS_Store"
    dependencies:
      - target: CoffeeScreen
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.gorita.coffee-screen-tests
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Coffee-Screen.app/Contents/MacOS/Coffee-Screen"
        BUNDLE_LOADER: "$(TEST_HOST)"
        GENERATE_INFOPLIST_FILE: YES

  CoffeeScreenUITests:
    type: bundle.ui-testing
    platform: macOS
    sources:
      - path: CoffeeScreenUITests
        excludes:
          - "**/.DS_Store"
    dependencies:
      - target: CoffeeScreen
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.gorita.coffee-screen-uitests
        TEST_TARGET_NAME: CoffeeScreen
        GENERATE_INFOPLIST_FILE: YES

schemes:
  CoffeeScreen:
    build:
      targets:
        CoffeeScreen: all
        CoffeeScreenTests: [test]
        CoffeeScreenUITests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - CoffeeScreenTests
        - CoffeeScreenUITests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
